version: '3.7'

services:
  mysql_db:
    container_name: "mysql_db_container"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: mysqldb.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "rootPass"
      MYSQL_DATABASE: "mysqlDB"
      MYSQL_USER: "erhan"
      MYSQL_PASSWORD: "pass"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  postgre_db:
    container_name: "postgre_db_container"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: postgresql.Dockerfile
    networks:
      - default
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  api:
    container_name:  "test_api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
      - postgre_db
    volumes:
      - .:/app/

networks:
  default:
volumes:
  mysql_data:
  postgresql_data: